module.exports = {
    INTERNAL_SERVER_ERROR : 500,
    SYNTAX_ERROR : 400,
    AUTHENTICATION_FAILED : 403,
    RESOURCE_NOT_FOUND : 404,
    METHOD_NOT_SUPPORTED: 405,
    CONFLICT : 409,
    WRONG_MEDIA_TYPE : 415,
    VALIDATION_FAILED : 422
};